package me.mudkip.moememos.ui.theme

import androidx.compose.ui.graphics.Color

// flomo 风格暖橙主题 — 纸感米白底 + 暖橙主色
val md_theme_light_primary = Color(0xFFE8590C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBCB)
val md_theme_light_onPrimaryContainer = Color(0xFF381500)
val md_theme_light_secondary = Color(0xFF77574B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCB)
val md_theme_light_onSecondaryContainer = Color(0xFF2C150C)
val md_theme_light_tertiary = Color(0xFF656036)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEDE4AE)
val md_theme_light_onTertiaryContainer = Color(0xFF201D00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF8F5)
val md_theme_light_onBackground = Color(0xFF231915)
val md_theme_light_surface = Color(0xFFFFF8F5)
val md_theme_light_onSurface = Color(0xFF231915)
val md_theme_light_surfaceVariant = Color(0xFFF5DED4)
val md_theme_light_onSurfaceVariant = Color(0xFF53443C)
val md_theme_light_outline = Color(0xFF86736A)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE5)
val md_theme_light_inverseSurface = Color(0xFF3A2E29)
val md_theme_light_inversePrimary = Color(0xFFFFB68F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFE8590C)

val md_theme_dark_primary = Color(0xFFFFB68F)
val md_theme_dark_onPrimary = Color(0xFF5B2400)
val md_theme_dark_primaryContainer = Color(0xFF7C3500)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_secondary = Color(0xFFE7BDAE)
val md_theme_dark_onSecondary = Color(0xFF442A20)
val md_theme_dark_secondaryContainer = Color(0xFF5D4035)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_tertiary = Color(0xFFD0C894)
val md_theme_dark_onTertiary = Color(0xFF363100)
val md_theme_dark_tertiaryContainer = Color(0xFF4D4821)
val md_theme_dark_onTertiaryContainer = Color(0xFFEDE4AE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F130D)
val md_theme_dark_onBackground = Color(0xFFF0DFD8)
val md_theme_dark_surface = Color(0xFF1F130D)
val md_theme_dark_onSurface = Color(0xFFF0DFD8)
val md_theme_dark_surfaceVariant = Color(0xFF53443C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2B8)
val md_theme_dark_outline = Color(0xFFA08C83)
val md_theme_dark_inverseOnSurface = Color(0xFF231915)
val md_theme_dark_inverseSurface = Color(0xFFF0DFD8)
val md_theme_dark_inversePrimary = Color(0xFFE8590C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB68F)


val seed = Color(0xFFE8590C)